version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - flask
      - fastapi

  flask:
    build: ./flask_app
    container_name: flask_service

  fastapi:
    build: ./fastapi_app
    container_name: fastapi_service
