name: CI - Flask and FastAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for Flask and FastAPI app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .

    - name: Run Flask unit tests
      run: pytest --cov=app --cov-report=term --cov-report=xml tests/
      working-directory: ./flask_app
      env:
        PYTHONPATH: app
        

    # - name: Install dependencies for FastAPI app
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install fastapi uvicorn pytest
    #   working-directory: ./fastapi_app

    - name: Run FastAPI unit tests
      run: pytest --cov=main --cov-report=term --cov-report=xml tests/
      working-directory: ./fastapi_app
      env:
        PYTHONPATH: main
